/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{html,js}", "./public/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        outline: "#8d9196",
        "on-secondary-container": "#c9b198",
        secondary: "#dcc2a9",
        "on-primary-container": "#7a90a3",
        primary: "#b3c9de",
        "primary-fixed": "#cfe5fb",
        "on-error": "#690005",
        "on-primary": "#1d3243",
        "on-secondary-fixed": "#261909",
        "surface-container-highest": "#363532",
        surface: "#141311",
        "error-container": "#93000a",
        "outline-variant": "#43474c",
        "on-tertiary-container": "#a78864",
        "on-surface-variant": "#c3c7cc",
        "surface-container-lowest": "#0f0e0c",
        "on-background": "#e6e2de",
        "primary-container": "#122838",
        "secondary-container": "#554430",
        "inverse-on-surface": "#31302e",
        "inverse-surface": "#e6e2de",
        "tertiary-fixed-dim": "#e4c09a",
        tertiary: "#e4c09a",
        "surface-container": "#20201d",
        "surface-container-high": "#2b2a27",
        "on-tertiary": "#422c10",
        "on-primary-fixed-variant": "#34495a",
        "on-error-container": "#ffdad6",
        "surface-bright": "#3a3936",
        "on-surface": "#e6e2de",
        "on-secondary-fixed-variant": "#554430",
        "tertiary-fixed": "#ffddb8",
        "surface-dim": "#141311",
        "on-secondary": "#3d2e1b",
        "on-tertiary-fixed-variant": "#5a4224",
        "on-primary-fixed": "#061d2d",
        "inverse-primary": "#4c6173",
        "secondary-fixed": "#f9dec3",
        background: "#141311",
        "primary-fixed-dim": "#b3c9de",
        "surface-variant": "#363532",
        error: "#ffb4ab",
        "surface-container-low": "#1c1b19",
        "tertiary-container": "#362207",
        "on-tertiary-fixed": "#2a1801",
        "surface-tint": "#b3c9de",
        "secondary-fixed-dim": "#dcc2a9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "16px",
        base: "8px",
        "stack-lg": "64px",
        gutter: "32px",
        "section-padding": "120px",
        "stack-md": "32px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg": ["Noto Serif"],
        "label-caps": ["Manrope"],
        "body-md": ["Manrope"],
        "display-xl": ["Noto Serif"],
        "headline-md": ["Noto Serif"],
        "body-lg": ["Manrope"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
